// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet.Models;

#nullable disable

namespace dotnet.Migrations
{
    [DbContext(typeof(TesTalContext))]
    partial class TesTalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("dotnet.Models.TesTal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nama");

                    b.HasKey("Id");

                    b.ToTable("TesTal");
                });
#pragma warning restore 612, 618
        }
    }
}
